# Test configuration for YAML functionality
server:
  port: "9090"
  host: "127.0.0.1"
  max_connections: 50
  worker_threads: 2
  request_timeout: 60
  max_request_size: 8388608
  idle_timeout: 600

logging:
  level: "DEBUG"
  file: ""
  access_log: true

auth:
  enabled: false
  require_api_key: false
  api_key_header: "X-API-Key"
  api_keys: []
  rate_limit:
    enabled: false
    max_requests: 200
    window_size: 120
  cors:
    enabled: true
    allow_credentials: false
    max_age: 3600
    allowed_origins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"
    allowed_methods:
      - "GET"
      - "POST"
      - "OPTIONS"
    allowed_headers:
      - "Content-Type"
      - "Authorization"

models: []

features:
  health_check: true
  metrics: true
  swagger: true
