# Sample Agent System Configuration for Kolosal Server
# This file demonstrates various agent types and their configurations

system:
  worker_threads: 8
  health_check_interval_seconds: 30
  log_level: "debug"
  global_settings:
    default_timeout_ms: 30000
    max_retries: 3
    enable_metrics: true

# Built-in functions that agents can use
functions:
  - name: "text_processing"
    type: "builtin"
    description: "Process and analyze text content"
    parameters:
      text: "Input text to process"
      operation: "Type of processing (tokenize, summarize, analyze)"
    timeout_ms: 10000
    
  - name: "data_analysis"
    type: "builtin"
    description: "Analyze structured data"
    parameters:
      data: "Input data in JSON format"
      analysis_type: "Type of analysis to perform"
    timeout_ms: 15000
    
  - name: "web_search"
    type: "external_api"
    description: "Search the web for information"
    endpoint: "https://api.search.com/v1/search"
    parameters:
      query: "Search query"
      limit: "Number of results"
    timeout_ms: 20000
    
  - name: "code_generation"
    type: "llm"
    description: "Generate code based on requirements"
    parameters:
      requirements: "Code requirements and specifications"
      language: "Programming language"
      style: "Coding style preference"
    timeout_ms: 45000

# Agent definitions
agents:
  # Research Assistant Agent
  - name: "research_assistant"
    type: "research"
    role: "Information researcher and analyzer"
    system_prompt: >
      You are a research assistant specialized in gathering, analyzing, and summarizing information.
      Your goal is to provide accurate, well-researched, and comprehensive answers to queries.
      Always cite sources when possible and indicate confidence levels in your findings.
    capabilities:
      - "web_search"
      - "text_processing" 
      - "data_analysis"
      - "information_synthesis"
    functions:
      - "web_search"
      - "text_processing"
      - "data_analysis"
    llm_config:
      model_name: "test-qwen-0.6b"
      api_endpoint: "http://localhost:8080/v1"
      instruction: "You are a research assistant. Provide accurate, well-researched, and comprehensive answers."
      temperature: 0.3
      max_tokens: 2048
      timeout_seconds: 45
      max_retries: 3
    auto_start: true
    max_concurrent_jobs: 3
    heartbeat_interval_seconds: 10
    custom_settings:
      search_depth: "comprehensive"
      fact_checking: "enabled"
      
  # Code Assistant Agent
  - name: "code_assistant"
    type: "development"
    role: "Software development assistant"
    system_prompt: >
      You are a senior software developer assistant. You help with code generation, review, 
      debugging, and optimization. You follow best practices and write clean, maintainable code.
      Always explain your code and suggest improvements when appropriate.
    capabilities:
      - "code_generation"
      - "code_review"
      - "debugging"
      - "optimization"
    functions:
      - "code_generation"
      - "text_processing"
    llm_config:
      model_name: "test-qwen-0.6b"
      api_endpoint: "http://localhost:8080/v1"
      instruction: "You are a software development assistant. Write clean, maintainable code and follow best practices."
      temperature: 0.2
      max_tokens: 4096
      timeout_seconds: 60
      max_retries: 2
    auto_start: true
    max_concurrent_jobs: 2
    heartbeat_interval_seconds: 15
      
  # Data Analyst Agent
  - name: "data_analyst"
    type: "analytics"
    role: "Data analysis and visualization specialist"
    system_prompt: >
      You are a data analyst who specializes in extracting insights from data.
      You can perform statistical analysis, create visualizations, and identify patterns.
      Always validate data quality and explain your analytical approach.
    capabilities:
      - "data_analysis"
      - "statistical_analysis"
      - "data_visualization"
      - "pattern_recognition"
    functions:
      - "data_analysis"
      - "text_processing"
    llm_config:
      model_name: "test-qwen-0.6b"
      api_endpoint: "http://localhost:8080/v1"
      instruction: "You are a data analyst. Extract insights from data and explain your analytical approach."
      temperature: 0.1
      max_tokens: 3072
      timeout_seconds: 40
      max_retries: 3
    auto_start: true
    max_concurrent_jobs: 4
    heartbeat_interval_seconds: 12
    custom_settings:
      visualization_library: "matplotlib"
      statistical_confidence: 0.95
      
  # Content Creator Agent
  - name: "content_creator"
    type: "creative"
    role: "Content creation and writing assistant"
    system_prompt: >
      You are a creative content writer who can produce engaging, well-structured content
      for various purposes including articles, documentation, marketing copy, and creative writing.
      Adapt your tone and style to match the intended audience and purpose.
    capabilities:
      - "content_writing"
      - "copywriting"
      - "technical_writing"
      - "creative_writing"
    functions:
      - "text_processing"
    llm_config:
      model_name: "test-qwen-0.6b"
      api_endpoint: "http://localhost:8080/v1"
      instruction: "You are a creative content writer. Adapt your tone and style to match the intended audience."
      temperature: 0.7
      max_tokens: 2048
      timeout_seconds: 35
      max_retries: 2
    auto_start: true
    max_concurrent_jobs: 3
    heartbeat_interval_seconds: 8
      
  # Project Manager Agent
  - name: "project_manager"
    type: "management"
    role: "Project coordination and management"
    system_prompt: >
      You are a project manager who helps coordinate tasks, manage timelines, and ensure
      efficient collaboration between team members and agents. You focus on planning,
      organizing, and tracking progress towards goals.
    capabilities:
      - "project_planning"
      - "task_coordination"
      - "progress_tracking"
      - "resource_management"
    functions:
      - "text_processing"
      - "data_analysis"
    llm_config:
      model_name: "test-qwen-0.6b"
      api_endpoint: "http://localhost:8080/v1"
      instruction: "You are a project manager. Focus on planning, organizing, and tracking progress."
      temperature: 0.4
      max_tokens: 2048
      timeout_seconds: 30
      max_retries: 3
    auto_start: true
    max_concurrent_jobs: 5
    heartbeat_interval_seconds: 20
    custom_settings:
      methodology: "agile"
      communication_style: "collaborative"
      
  # Quality Assurance Agent
  - name: "qa_specialist"
    type: "quality_assurance"
    role: "Quality assurance and testing specialist"
    system_prompt: >
      You are a QA specialist focused on ensuring quality, identifying issues, and
      improving processes. You perform testing, validation, and provide feedback
      to maintain high standards across all deliverables.
    capabilities:
      - "testing"
      - "validation"
      - "quality_control"
      - "process_improvement"
    functions:
      - "text_processing"
      - "data_analysis"
    llm_config:
      model_name: "test-qwen-0.6b"
      api_endpoint: "http://localhost:8080/v1"
      instruction: "You are a QA specialist. Focus on quality, testing, and process improvement."
      temperature: 0.2
      max_tokens: 2048
      timeout_seconds: 25
      max_retries: 3
    auto_start: false
    max_concurrent_jobs: 2
    heartbeat_interval_seconds: 15
    custom_settings:
      testing_approach: "comprehensive"
      quality_standards: "high"
      
  # Response Test Agent
  - name: "response_test_agent"
    type: "general"
    role: "General purpose test agent for response validation"
    system_prompt: >
      You are a helpful AI assistant designed for testing purposes. You provide clear,
      accurate, and concise responses to various types of questions and requests.
      You can handle greetings, math problems, coding tasks, and explanations.
    capabilities:
      - "general_assistance"
      - "math_calculation"
      - "code_generation"
      - "explanation"
    functions:
      - "text_processing"
      - "code_generation"
    llm_config:
      model_name: "test-qwen-0.6b"
      api_endpoint: "http://localhost:8080/v1"
      instruction: "You are a helpful AI assistant. Provide clear, accurate, and concise responses."
      temperature: 0.5
      max_tokens: 1024
      timeout_seconds: 30
      max_retries: 3
    auto_start: true
    max_concurrent_jobs: 5
    heartbeat_interval_seconds: 10
    custom_settings:
      response_format: "conversational"
      enable_testing: true
